version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: retailrocket_events
      - name: retailrocket_categories
      - name: indonesian_holidays
      - name: google_trends
      - name: bps_income
